language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "KpBjzaCzFHo4+MhNQrP0Aw7817Jl1U5s5tmXfEcEiO/sr+9sb4dSMoY5Bppkw93C88PaoIVaoOM4q/zz/X0oVyTqydJV697y+edkM6yyi65H8pYPO3SPSfn/gDNU5Qcpg9C0/ZMI0GLBECcqJOSqOqVQqouC0g3eKvLAGNRPxsscLgtp8AIUb44i09J20R1M8QpeYe3BnmmB4ZZycW51YWWg4M+BSIibxTyLS3q4lqZgpsBKdjLRy0wU7guu38Jty8XAjgw5SoHYlw/XFSkXz3MDOE6UUwYJ4LXZ5Rx2lK6O0DiWznwAd0p2ofYWmFmXmdG+oBkNcW7YPOPmD/FCPoh1pZFYTkoOj/1mgRx5wYW6oHWHQ+dXX30HQv30sKxfHc4gkvs6JTluPKi1XYMZq1USh0eXM3tDpEzcPJoXDWE1Awh0JBw2+dupf6EzI9YzKkco5G0/S8+Ovff3hlO4KlpWgPABAvIoeRIEPcqVlVp8ndqnoI9uZlRWEwQEEUgywx/PX80zKx4cRe+tKbXeBK1IwRnuS5g4xd0MgCrwQfA3ctCwnw/AfuFgso4d4DQBqGKiR9HckGLltgAJU84ZQV9DH+qeEhwXxyTI2eDDHH0M3IxVvfzmtaphhzDoB1RSkl3nxf9cHmg2mwo+vCHt/Z+JWQb8FxMvGlPlmO5tbkM="
